version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_AI_API_URL=http://localhost:8001
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - ai-service

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CORS_ORIGIN=http://localhost:3000
      - AI_SERVICE_URL=http://ai-service:8001
      - JWT_SECRET=your-super-secret-jwt-key-here
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/social_ai
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - ai-service

  ai-service:
    build:
      context: ../ai
      dockerfile: ../docker/Dockerfile.ai
    ports:
      - "8001:8001"
    environment:
      - PYTHON_ENV=development
      - PORT=8001
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../ai:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - redis
      - ollama

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=social_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  postgres_data:
  redis_data:
  ollama_data:
